### ISSUE TITLE
Update to 0.10 and merge into diesel main repo

### ISSUE THREAD

**Issue by killercup** [Phrohdoh/rs-diesel-sqlite#2]
I'd love to have this in the main repo next to the postgres examples. I'd be up to merging this in if it's okay with you.

**Comment by Phrohdoh** [comment]
Absolutely!

I'll get this working on 0.10 and open a PR.

**Comment by Phrohdoh** [comment]
Here is some context as to why this hasn't happened yet: https://gitter.im/diesel-rs/diesel?at=58938fe72ff29dec066ccb34

I'd like to see it merged but don't have the time currently to learn the ins and outs of diesel's setup.
